site_name: The Second Language Research Toolkit
markdown_extensions:
  - attr_list
  - md_in_html

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    logo: fontawesome/solid/book
  favicon: favicon.png

  features:
    - header.autohide

      # - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level sections are shown as tabs
    - navigation.tabs.sticky # tabs always show
    - navigation.sections # sections are rendered as groups in the sidebar
    - navigation.expand # all sections are expanded
    - navigation.indexes # link an index.md page to a section
    - navigation.top # show back-to-top button
    - toc.integrate # show table of contents to navigation panel
    - header.autohide

    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button

  font:
    text: Roboto

  hide:
    - footer

  extra:
    generator: false

  extra_css:
    - stylesheets/extra.css

  extra_javascript:
    - "javascripts/removeCredits.js"
# copyright: Copyright &copy; 2016 - 2020 Martin Donath

